version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
      - "8441:8441"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount file cấu hình nginx
      - ./nginx/certs/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro # Mount chứng chỉ SSL
      - ./nginx/certs/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro # Mount khóa SSL
    command: >
      /bin/bash -c "update-ca-certificates && nginx -g 'daemon off;'"
    networks:
      - app-network

  graylog:
    image: graylog/graylog:4.3
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=https://dockerapi.com:8441/graylog/
      - GRAYLOG_PASSWORD_SECRET=Hieupromen@201198
      - GRAYLOG_ROOT_PASSWORD_SHA2=4C91A148B34B647FE25A247126B0DB5B716C032A28787236F567057FF8BFF29D
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"  # Graylog web interface
    networks:
      - app-network
    volumes:
      - graylog_data:/usr/share/graylog/data

  mongo:
    image: mongo:4.4
    ports:
      - "20119:27017" 
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - app-network
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    command: >
      redis-server --port 6380 --requirepass "Hieu@201198" --user HieuPc
    ports:
      - "6380:6380"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  graylog_data:
  es_data:
